name: Flutter

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ## Initialise Github actions base
      - name: Clone repository
        uses: actions/checkout@v4
      ## Setup flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      ## Build and test the app
        - run: flutter pub get
        - run: flutter test